import { NextResponse } from "next/server";
import { BOTROW_CONTRACT_ADDRESS } from "@/constants/contract";

/**
 * POST /api/ai/agent
 * Botrow Global AI Concierge
 */
export async function POST(req: Request) {
  try {
    const geminiKey = process.env.GEMINI_API_KEY;

    if (!geminiKey) {
      return NextResponse.json(
        { error: "Missing GEMINI_API_KEY environment variable" },
        { status: 500 }
      );
    }

    const { message, userContext, history } = await req.json();

    if (!message) {
      return NextResponse.json({ error: "Message prompt is required" }, { status: 400 });
    }

    // Convert the user's fetched data into context for the AI
    const contextText = userContext
      ? `[User Account Information]
- Wallet Address: ${userContext.walletAddress || "Unknown"}
- Name: ${userContext.profile?.fullName || "Not set"}

[Recent Purchases (Buyer Orders)]
${userContext.buyerOrders && userContext.buyerOrders.length > 0 
  ? userContext.buyerOrders.map((o: any) => `- Escrow #${o.escrowId} | Product: ${o.productTitle} | Amount: ${o.amount} BOT | Status: ${o.status} | Seller: ${o.seller}`).join("\n") 
  : "No recent purchases found."}

[Recent Sales (Seller Orders)]
${userContext.sellerOrders && userContext.sellerOrders.length > 0 
  ? userContext.sellerOrders.map((o: any) => `- Escrow #${o.escrowId} | Product: ${o.productTitle} | Amount: ${o.amount} BOT | Status: ${o.status} | Buyer: ${o.buyer}`).join("\n") 
  : "No recent sales found."}

[Active Marketplace Listings]
${userContext.marketplaceProducts && userContext.marketplaceProducts.filter((p: any) => p.status === "ACTIVE").length > 0
  ? userContext.marketplaceProducts.filter((p: any) => p.status === "ACTIVE").map((p: any) => `- ${p.title} | ${p.price} BOT | Trust Score: ${p.trustScore || "N/A"}/100 | Condition: ${p.condition} | Link ID: ${p.id}`).join("\n")
  : "No active products available."}

[Botrow Escrow Global Rules]
- Smart Contract: ${BOTROW_CONTRACT_ADDRESS}
- Funds are locked until the physical item is delivered.
- Sellers must ship items promptly to avoid disputes.
`
      : "No user context provided. Answer as a general Botrow marketplace assistant.";

    const systemPrompt = `You are Botrow AI, the official global Concierge for the Botrow marketplace built on BOT Chain 677.

Your Core Responsibilities & Response Style:
- Act as a highly intelligent, polite, and helpful personal assistant for the user.
- If the user asks about their specific orders, sales, or account, reference the [User Account Information] block provided to you.
- Never invent orders that don't exist in the context block. If they ask about an order that isn't listed, politely tell them you cannot find it.
- Maintain a friendly, conversational tone. Keep responses concise unless asked for details.`;

    const modelsToTry = ["gemini-3.5-flash", "gemini-2.5-flash"];
    let lastError = "No text response generated by Botrow AI";

    const previousTurns = Array.isArray(history)
      ? history.map((item: { role: string; text: string }) => ({
          role: item.role === "assistant" || item.role === "model" ? "model" : "user",
          parts: [{ text: item.text }],
        }))
      : [];

    const currentTurn = {
      role: "user",
      parts: [{ text: `${contextText}\n\nUser Question:\n${message}` }],
    };

    for (const modelName of modelsToTry) {
      try {
        const googleRes = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${geminiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              systemInstruction: {
                parts: [{ text: systemPrompt }],
              },
              contents: [...previousTurns, currentTurn],
              generationConfig: {
                temperature: 0.7,
                topP: 0.95,
                topK: 40,
                maxOutputTokens: 4096,
              },
            }),
          }
        );

        if (googleRes.ok) {
          const googleData = await googleRes.json();
          const aiReply = googleData?.candidates?.[0]?.content?.parts?.[0]?.text;
          
          if (aiReply) {
            return NextResponse.json({
              success: true,
              modelUsed: modelName,
              reply: aiReply.trim(),
            });
          }
        } else {
          lastError = `API returned ${googleRes.status} for ${modelName}`;
        }
      } catch (err: any) {
        lastError = `Network error for ${modelName}: ${err.message}`;
      }
      console.warn(`[Botrow AI Agent] ${modelName} failed, falling back... Error: ${lastError}`);
    }

    return NextResponse.json(
      { success: false, error: lastError },
      { status: 500 }
    );
  } catch (err: any) {
    console.error("[Botrow AI Agent Error]:", err);
    return NextResponse.json(
      { success: false, error: String(err?.message || err) },
      { status: 500 }
    );
  }
}
