import { Product, Order, UserProfile } from "../types";

export const MOCK_CURRENT_USER: UserProfile = {
  walletAddress: "0x71C...89E2",
  username: "Alex_V7",
  avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
  aiTrustScore: 98,
  totalSales: 24,
  totalPurchases: 12,
  activeEscrowBalanceBot: 4500,
  totalRevenueBot: 18450.5,
  joinDate: "January 2026",
  verifiedBadge: true,
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    onchainListingId: 101,
    title: "Gently Used Sony Alpha a7 IV Camera + 24-70mm f/2.8 Lens",
    description: "Everyday person-to-person sale from a passionate photographer. Only ~4,200 mechanical shutter count. Minor surface scuffs on lens hood, optics are crystal clean. Escrow protects buyer to inspect working sensor before fund release.",
    priceBot: 420,
    usdEquivalent: 1890,
    category: "Electronics & Tech",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80",
    sellerAddress: "0x8920...F12A",
    sellerName: "David_Photo",
    sellerAvatar: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80",
    sellerTrustScore: 99,
    status: "ACTIVE",
    createdAt: "2026-08-01T10:30:00Z",
    aiAnalysis: {
      trustScore: 99,
      riskLevel: "LOW",
      priceEstimateBot: 430,
      suggestedTags: ["Used Camera", "Sony a7 IV", "Photography", "Electronics"],
      isVerifiedByGemini: true,
    },
    specifications: {
      "Condition": "Used / Excellent (Normal Wear)",
      "Shutter Count": "~4,200 actuations (Rated for 200k)",
      "Included": "Camera Body, Sony Lens, 2 OEM Batteries, Charger",
      "Escrow Window": "7-Day Inspection upon postal arrival",
    },
  },
  {
    id: "prod-2",
    onchainListingId: 102,
    title: "Pre-Owned Herman Miller Aeron Chair (Size B, Fully Loaded)",
    description: "Moving out of my studio apartment and selling my authentic Herman Miller ergonomic office chair. Functions flawlessly with PostureFit SL lumbar support and adjustable arms. No fabric sags or tears.",
    priceBot: 145,
    usdEquivalent: 652,
    category: "Home & Everyday",
    image: "https://images.unsplash.com/photo-1580481077494-e3299ac2fef6?auto=format&fit=crop&w=800&q=80",
    sellerAddress: "0x34A1...90B3",
    sellerName: "Sarah_Design",
    sellerAvatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80",
    sellerTrustScore: 97,
    status: "ACTIVE",
    createdAt: "2026-08-02T14:15:00Z",
    aiAnalysis: {
      trustScore: 97,
      riskLevel: "LOW",
      priceEstimateBot: 150,
      suggestedTags: ["Used Furniture", "Herman Miller", "Office", "Home"],
      isVerifiedByGemini: true,
    },
    specifications: {
      "Condition": "Used / Very Good (Minor frame scuff)",
      "Size & Configuration": "Size B (Medium) / Fully Adjustable",
      "Authenticity": "Serial sticker intact under seat chassis",
      "Delivery": "Local meetup or freight courier secured by escrow",
    },
  },
  {
    id: "prod-3",
    onchainListingId: 103,
    title: "Vintage Rolex GMT-Master II ('Pepsi' Bezel, Ref: 16710)",
    description: "Pre-owned luxury timepiece traded directly between collectors. Comes complete with original presentation box and chronometer certificate. Gemini AI confirms serial engraving authenticity and fair secondary market valuation.",
    priceBot: 3100,
    usdEquivalent: 13950,
    category: "Fashion & Apparel",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
    sellerAddress: "0x55B2...33D4",
    sellerName: "Marco_Timepieces",
    sellerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    sellerTrustScore: 98,
    status: "ACTIVE",
    createdAt: "2026-08-03T09:00:00Z",
    aiAnalysis: {
      trustScore: 98,
      riskLevel: "LOW",
      priceEstimateBot: 3150,
      suggestedTags: ["Luxury Watch", "Used Rolex", "Fashion", "Collectibles"],
      isVerifiedByGemini: true,
    },
    specifications: {
      "Condition": "Pre-Owned / Collector Grade (Unpolished)",
      "Case Material": "Oystersteel (40mm)",
      "Movement": "Calibre 3185 Automatic",
      "Protection": "Botrow Zero-Trust Escrow Inspection Window",
    },
  },
  {
    id: "prod-4",
    onchainListingId: 104,
    title: "Artisan Spanish Iberian Ham & Reserve Extra Virgin Olive Oil Bundle",
    description: "Direct person-to-person culinary harvest from family estate in Andalusia, Spain. Includes a cured acorn-fed Iberian ham leg (~7kg) and six bottles of cold-pressed harvest olive oil. Shipped directly from farm with freshness guarantees.",
    priceBot: 120,
    usdEquivalent: 540,
    category: "Gourmet & Foodstuff",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    sellerAddress: "0x9099...11A1",
    sellerName: "Elena_Andalusia",
    sellerAvatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80",
    sellerTrustScore: 95,
    status: "ACTIVE",
    createdAt: "2026-07-28T18:20:00Z",
    aiAnalysis: {
      trustScore: 96,
      riskLevel: "LOW",
      priceEstimateBot: 125,
      suggestedTags: ["Foodstuff", "Gourmet", "Iberian Ham", "Olive Oil"],
      isVerifiedByGemini: true,
    },
    specifications: {
      "Condition": "Fresh / Artisanal Small Batch Harvest",
      "Origin": "Sierra de Aracena, Spain (Direct Producer)",
      "Packaging": "Vacuum preservation with thermal cool packs",
      "Quality Assurance": "Protected Designation of Origin (DOP)",
    },
  },
  {
    id: "prod-5",
    onchainListingId: 105,
    title: "Apple MacBook Pro M4 Max (16-inch, 64GB RAM, 2TB SSD)",
    description: "Brand new factory sealed high-performance notebook. Selling because my employer supplied an identical machine. Botrow smart contract holds your deposit until you unwrap, turn on, and verify the serial number with Apple.",
    priceBot: 850,
    usdEquivalent: 3825,
    category: "Electronics & Tech",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
    sellerAddress: "0x8920...F12A",
    sellerName: "Alex_Dev_SF",
    sellerAvatar: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=150&q=80",
    sellerTrustScore: 99,
    status: "ACTIVE",
    createdAt: "2026-08-01T10:30:00Z",
    aiAnalysis: {
      trustScore: 99,
      riskLevel: "LOW",
      priceEstimateBot: 845,
      suggestedTags: ["New Laptop", "MacBook Pro", "Apple", "Computers"],
      isVerifiedByGemini: true,
    },
    specifications: {
      "Condition": "Brand New / Factory Sealed",
      "Processor": "Apple M4 Max (16-core CPU)",
      "Memory": "64GB Unified Memory / 2TB SSD Storage",
      "Shipping": "Insured Express Courier (Signature Required)",
    },
  },
  {
    id: "prod-6",
    onchainListingId: 106,
    title: "Pre-Owned Nike Air Jordan 1 Retro 'Chicago' (1985 Release, Size 10.5)",
    description: "Authentic vintage collector sneakers owned since the late 1980s. Well preserved in an archival UV-blocking vault. Zero-risk escrow gives buyer ample time to authenticate materials with an independent verifier before settlement.",
    priceBot: 480,
    usdEquivalent: 2160,
    category: "Collectibles & Art",
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80",
    sellerAddress: "0x11B4...77C9",
    sellerName: "Marcus_Vintage",
    sellerAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
    sellerTrustScore: 96,
    status: "ACTIVE",
    createdAt: "2026-07-30T11:00:00Z",
    aiAnalysis: {
      trustScore: 95,
      riskLevel: "LOW",
      priceEstimateBot: 475,
      suggestedTags: ["Used Sneakers", "Vintage", "Jordan 1", "Collectibles"],
      isVerifiedByGemini: true,
    },
    specifications: {
      "Condition": "Pre-Owned / Archival Collector State",
      "Size": "US 10.5 / EU 44.5",
      "Provenance": "Original receipt and late-80s photographs included",
      "Protection": "Botrow 100% Counterfeit Protection Guarantee",
    },
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-881",
    onchainOrderId: 501,
    product: MOCK_PRODUCTS[0],
    buyerAddress: "0x71C...89E2",
    sellerAddress: MOCK_PRODUCTS[0].sellerAddress,
    amountBot: 420,
    status: "LOCKED",
    timestamp: "2026-08-03T11:45:00Z",
  },
  {
    id: "ord-882",
    onchainOrderId: 502,
    product: MOCK_PRODUCTS[3],
    buyerAddress: "0x44D...11A9",
    sellerAddress: "0x71C...89E2", // Sold by current user
    amountBot: 120,
    status: "DELIVERED",
    timestamp: "2026-08-01T09:20:00Z",
    deliveryConfirmedAt: "2026-08-02T16:30:00Z",
  },
];
