import { NextResponse } from "next/server";
import { BOTROW_CONTRACT_ADDRESS } from "@/constants/contract";

/**
 * POST /api/ai/chat
 * Botrow AI Assistant — Gemini 3.5 Flash (Server-side REST)
 */
export async function POST(req: Request) {
  try {
    const geminiKey = process.env.GEMINI_API_KEY;

    if (!geminiKey) {
      return NextResponse.json(
        { error: "Missing GEMINI_API_KEY environment variable" },
        { status: 500 }
      );
    }

    const { message, productContext, history } = await req.json();

    if (!message) {
      return NextResponse.json({ error: "Message prompt is required" }, { status: 400 });
    }

    // Structured Product & Escrow Brief
    const contextText = productContext
      ? `[Current Product Listing Brief]
- Title: ${productContext.title || "N/A"}
- Price: ${productContext.priceBot ? `${productContext.priceBot} BOT` : "N/A"}
- Category: ${productContext.category || "N/A"}
- Condition: ${productContext.condition || "N/A"}
- Seller: ${productContext.sellerName || "Individual Merchant"} (${productContext.sellerWallet || "N/A"})
- Seller Trust Score: ${productContext.sellerTrustScore ? `${productContext.sellerTrustScore}/100` : "90/100"}
- Location: ${productContext.location || "Global Dispatch"}
- Description: ${productContext.description || "N/A"}

[Botrow Escrow Security Rules]
- Smart Contract: ${BOTROW_CONTRACT_ADDRESS}
- Buyer funds remain 100% locked on BOT Chain 677 until physical package receipt.
- Seller cannot withdraw funds early.
- Buyer has full rights to inspect the physical item and open a dispute before confirming delivery.
`
      : "No specific product context provided.";

    const systemPrompt = `You are Botrow AI, an expert Web3 shopping and escrow assistant for the Botrow marketplace built on BOT Chain 677.

Your Core Responsibilities & Response Style:
- Answer thoroughly, naturally, and knowledgeably like a top shopping consultant.
- When evaluating products, explain your reasoning, advantages, potential disadvantages, and any item condition or pricing risks.
- Clearly reference the supplied product listing brief and explain how Botrow smart contract escrow protects the buyer.
- If the user's question is vague, answer helpfully and ask ONE clear clarifying question instead of guessing.
- Do not fabricate missing product specifications, seller reputation, or fake blockchain transactions. If information is missing, clearly state that it is unavailable.
- Maintain a friendly, conversational tone rather than a robotic fixed template.`;

    const modelsToTry = ["gemini-3.5-flash", "gemini-2.5-flash"];
    let lastError = "No text response generated by Botrow AI";

    // Build multi-turn conversation contents
    const previousTurns = Array.isArray(history)
      ? history.map((item: { role: string; text: string }) => ({
          role: item.role === "assistant" || item.role === "model" ? "model" : "user",
          parts: [{ text: item.text }],
        }))
      : [];

    const currentTurn = {
      role: "user",
      parts: [{ text: `${contextText}\n\nUser Question:\n${message}` }],
    };

    for (const modelName of modelsToTry) {
      try {
        const googleRes = await fetch(
          `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${geminiKey}`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              systemInstruction: {
                parts: [{ text: systemPrompt }],
              },
              contents: [...previousTurns, currentTurn],
              generationConfig: {
                temperature: 0.8,
                topP: 0.95,
                topK: 40,
                maxOutputTokens: 4096,
              },
            }),
          }
        );

        if (googleRes.ok) {
          const googleData = await googleRes.json();
          const aiReply = googleData?.candidates?.[0]?.content?.parts?.[0]?.text;
          
          if (aiReply) {
            return NextResponse.json({
              success: true,
              modelUsed: modelName,
              reply: aiReply.trim(),
            });
          }
        } else {
          lastError = `API returned ${googleRes.status} for ${modelName}`;
        }
      } catch (err: any) {
        lastError = `Network error for ${modelName}: ${err.message}`;
      }
      console.warn(`[Botrow AI Chat] ${modelName} failed, falling back... Error: ${lastError}`);
    }

    return NextResponse.json(
      { success: false, error: lastError },
      { status: 500 }
    );
  } catch (err: any) {
    console.error("[Botrow AI Chat Error]:", err);
    return NextResponse.json(
      { success: false, error: String(err?.message || err) },
      { status: 500 }
    );
  }
}
